name: Vowel Frequency CI Workflow

on:
  push:
    branches:
      - main

jobs:
  analyze_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Build and Run Docker Action
        run: |
          docker build -t frequency-action .
          docker run -e GITHUB_USER="${{ github.actor }}" -v ${{ github.workspace }}:/app frequency-action